export const postData = [
  {
    id: 1,
    description: " love to all one hate to no one ",
    photo: "../../assets/Person/pro.jpeg",
    date: "1 min ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    description: " love to all one hate to no one ",
    photo: "../../assets/Person/pro.jpeg",
    date: "1 min ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    description: " love to all one hate to no one ",
    photo: "../../assets/Person/pro.jpeg",
    date: "1 min ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    description: " love to all one hate to no one ",
    photo: "../../assets/Person/pro.jpeg",
    date: "1 min ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    description: " love to all one hate to no one ",
    photo: "../../assets/Person/pro.jpeg",
    date: "1 min ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
];
